name: adary
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 2.0.16+23
version: 2.0.17+9

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  shared_preferences: ^2.3.2
  http_parser: ^4.0.2
  http: ^1.1.0
  image_picker: ^1.2.1
  connectivity_plus: ^5.0.1
  flutter_svg: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  infinite_scroll_pagination: ^4.0.0
  dropdown_button2: ^2.3.9
  dio: ^5.7.0
  easy_radio: ^0.0.3
  custom_date_range_picker: ^1.1.0
  flutter_easyloading: ^3.0.5
  logger: ^2.4.0
  internet_connection_checker_plus: ^2.2.0
  get_it: ^8.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  syncfusion_flutter_datepicker: ^28.2.11+1
  hijri_calendar: ^1.0.7+7
  awesome_dialog: ^3.2.1
  hijri: ^3.0.0
  file_picker: ^8.1.3
  time_picker_spinner: ^1.0.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  printing: ^5.13.4
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  lottie: ^3.1.3
  jhijri_picker: ^1.0.1
  # islamic_hijri_calendar: ^0.0.3
  table_calendar: ^3.1.3
  pdfrx: ^2.2.24
  flutter_pdfview: ^1.4.4
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.4.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# flutter_native_splash:
#   # اللون الأبيض (خلفية احتياطية لو الصورة ماجتش)
#   color: "#FFFFFF"
  
#   # استخدم background_image عشان تتمدد لكامل الشاشة
#   background_image: "assets/splash.png"
  
#   # أخفي شريط الحالة
#   fullscreen: true

#   # -------------------------------------------------
#   # للأجهزة القديمة (أندرويد 11 فأقل و iOS)
#   # background_image بتتمدد تلقائيًا، بس ممكن تتحكم في الـ gravity
#   # -------------------------------------------------
#   android_gravity: fill       # تملأ كامل الشاشة (أندرويد)
#   ios_content_mode: scaleToFill  # تملأ كامل الشاشة (iOS)
#   web_image_mode: cover       # تغطية كامل الشاشة (Web)

#   # -------------------------------------------------
#   # لأندرويد 12+ (للأسف ما يدعمش background_image)
#   # -------------------------------------------------
#   android_12:
#     color: "#FFFFFF"          # خلفية بيضا فقط – مفيش حل لصورة خلفية كاملة هنا
#     # ما تحطش image جوه android_12 عشان متفاجئش بدائرة في النص

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon1.png"
  remove_alpha_ios: true
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/splash.png
    - assets/icons/
    - assets/lang/
    - assets/appData/privacy_policy.json
  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/AbhayaLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AbhayaLibre-ExtraBold.ttf
          weight: 800
    - family: PingARLT
      fonts:
        - asset: assets/fonts/PingAR+LT-Black.otf
          weight: 900
        - asset: assets/fonts/PingAR+LT-Bold.otf
          weight: 700
        - asset: assets/fonts/PingAR+LT-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/PingAR+LT-Hairline.otf
          weight: 100
        - asset: assets/fonts/PingAR+LT-Heavy.otf
          weight: 800
        - asset: assets/fonts/PingAR+LT-Light.otf
          weight: 300
        - asset: assets/fonts/PingAR+LT-Medium.otf
          weight: 500
        - asset: assets/fonts/PingAR+LT-Regular.otf
          weight: 400
        - asset: assets/fonts/PingAR+LT-Thin.otf
          weight: 100
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 900
    - family: BahijTheSansArabic
      fonts:
        - asset: assets/fonts/Bahij_TheSansArabic-Bold.ttf
          weight: 700
  